# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GkchRNiJLMHT25brc9KiKPUdvw_xSY8E
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/health care diabetes.csv')

print(df)

df.head()

df.shape
df.columns
df.info()

df.describe()

df.isnull().sum()

df = df.dropna()

df.duplicated().sum()

df = df.drop_duplicates()

df.hist(figsize=(12,10))
plt.show()

for col in df.columns:
    plt.figure()
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

sns.countplot(x='Outcome', data=df)
plt.title("Count Plot of Outcome")
plt.show()

for col in df.columns:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

corr = df.corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

df.skew()

df['Age'] = np.log1p(df['Age'])

